train:
  sl:
    learning_rate: 0.0001
    epochs: 100
    save_path: './pretrained/supervised_learning'
    optim: 'ADAM'
    scheduler: {'multistep': {"milestones": [30, 80], "gamma": 0.1}}
    dataset:
      data_path: './data/'
      train_val_ratio: 0.8
      num_workers: 2
      batch_size: 64
  rl:
    episodes: 10000
    save_path: './pretrained/reinforcement_learning'
    optim:
      actor: 'ADAM'
      critic: 'ADAM'
    learning_rate:
      actor: 0.0001
      critic: 0.0001
    scheduler:
      actor : {'multistep': {"milestones": [30, 80], "gamma": 0.1}}
      critic : {'multistep': {"milestones": [30, 80], "gamma": 0.1}}
    model:
      timesteps_per_batch: 4000
      max_timesteps_per_episode: 400
      n_updates_per_iteration: 5
  


  device: 'cpu'
  
